namespace Dungeon.Domain.Exceptions;

/// <summary>
/// The run was generated by an algorithm version this build no longer contains, so its
/// seed can no longer be replayed identically.
/// </summary>
public sealed class UnsupportedGeneratorVersionException(int requestedVersion, int currentVersion)
    : DomainException(
        $"Dungeon generator version {requestedVersion} is not supported (current version: {currentVersion})."
    );
